#!/usr/bin/env python3
"""Generates the CLDR tables embedded in each port from data/cldr47.json.

    python3 scripts/gen_ports.py          # writes the five generated files
    python3 scripts/gen_ports.py --check  # fails if any generated file is stale

Generated files (do not edit by hand):
  rust/src/data.rs, typescript/src/data.ts, python/lomboklocale/_data.py,
  go/data.go, php/src/Data.php
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = json.loads((ROOT / "data" / "cldr47.json").read_text(encoding="utf-8"))
HEADER = "Generated by scripts/gen_ports.py from data/cldr47.json (CLDR %s). Do not edit." % SRC["cldr"]
CATS = {"zero": 0, "one": 1, "two": 2, "few": 3, "many": 4}


def compact():
    """The structure every port receives (JSON-compatible)."""
    return {
        "cldr": SRC["cldr"],
        "currencyDigits": SRC["currencyDigits"],
        "plurals": SRC["plurals"],
        "ordinals": SRC["ordinals"],
        "locales": SRC["data"],
    }


def rs_str(s):
    return json.dumps(s, ensure_ascii=False)


def rust():
    d = compact()
    out = ["// " + HEADER, "use crate::tables::*;", ""]
    out.append('pub const CLDR_VERSION: &str = %s;' % rs_str(d["cldr"]))
    out.append("pub static CURRENCY_DIGITS: &[(&str, u8)] = &[%s];" % ", ".join(
        "(%s, %d)" % (rs_str(k), v) for k, v in sorted(d["currencyDigits"].items())))

    def rules(table):
        rows = []
        for loc, entries in sorted(table.items()):
            cats = []
            for cat, groups in entries:
                gs = []
                for rels in groups:
                    rs = ["Rel { op: b'%s', modulus: %d, negated: %s, ranges: &[%s] }" % (
                        op, m, "true" if neg else "false", ", ".join("(%d, %d)" % (lo, hi) for lo, hi in ranges))
                        for op, m, neg, ranges in rels]
                    gs.append("&[%s]" % ", ".join(rs))
                cats.append("(%d, &[%s])" % (CATS[cat], ", ".join(gs)))
            rows.append("    (%s, &[%s])," % (rs_str(loc), ", ".join(cats)))
        return rows
    out.append("pub static PLURALS: RuleTable = &[")
    out += rules(d["plurals"])
    out.append("];")
    out.append("pub static ORDINALS: RuleTable = &[")
    out += rules(d["ordinals"])
    out.append("];")
    out.append("pub static LOCALES: &[(&str, LocaleData)] = &[")
    for loc, x in sorted(d["locales"].items()):
        syms = ", ".join("(%s, %s, %s, %s)" % (rs_str(c), rs_str(v[0]), "true" if v[1] else "false",
                                                "true" if v[2] else "false") for c, v in sorted(x["currencySymbols"].items()))
        out.append("    (%s, LocaleData {" % rs_str(loc))
        for k, f in [("decimal", "decimal"), ("group", "group"), ("minus", "minus"), ("percent", "percent"),
                     ("infinity", "infinity"), ("nan", "nan"), ("decimalPattern", "decimal_pattern"),
                     ("percentPattern", "percent_pattern"), ("currencyPattern", "currency_pattern"), ("era", "era")]:
            out.append("        %s: %s," % (f, rs_str(x[k])))
        out.append("        min_grouping: %d," % x["minGrouping"])
        out.append("        currency_symbols: &[%s]," % syms)
        out.append("        date_formats: [%s]," % ", ".join(rs_str(x["dateFormats"][s]) for s in ("full", "long", "medium", "short")))
        out.append("        months: [%s]," % ", ".join("[%s]" % ", ".join(rs_str(m) for m in row) for row in x["months"]))
        out.append("        days: [%s]," % ", ".join("[%s]" % ", ".join(rs_str(m) for m in row) for row in x["days"]))
        out.append("    }),")
    out.append("];")
    return "\n".join(out) + "\n"


TS_TYPES = """/** One plural relation: [operand, modulus (0 = none), negated (1 = !=), inclusive ranges]. */
export type Rel = [string, number, number, [number, number][]];
/** Rules of one locale: [category, OR groups of AND relations] in CLDR order. */
export type Rules = [string, Rel[][]][];
/** Number and date data of one locale. */
export interface LocaleData {
    currencyPattern: string;
    currencySymbols: Record<string, [string, number, number]>;
    dateFormats: { full: string; long: string; medium: string; short: string };
    days: [string[], string[]];
    decimal: string;
    decimalPattern: string;
    era: string;
    group: string;
    infinity: string;
    minGrouping: number;
    minus: string;
    months: [string[], string[]];
    nan: string;
    percent: string;
    percentPattern: string;
}
export interface CldrData {
    cldr: string;
    currencyDigits: Record<string, number>;
    locales: Record<string, LocaleData>;
    ordinals: Record<string, Rules>;
    plurals: Record<string, Rules>;
}
"""


def ts():
    return "// %s\n%s\nexport const DATA: CldrData = %s;\n" % (
        HEADER, TS_TYPES, json.dumps(compact(), ensure_ascii=False, sort_keys=True, separators=(",", ":")))


def py():
    return '"""%s"""\nimport json\n\nDATA = json.loads(%r)\n' % (
        HEADER, json.dumps(compact(), ensure_ascii=False, sort_keys=True, separators=(",", ":")))


def go():
    blob = json.dumps(compact(), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return "// Code generated by scripts/gen_ports.py from data/cldr47.json (CLDR %s). DO NOT EDIT.\n\npackage lomboklocale\n\nconst cldrJSON = %s\n" % (
        SRC["cldr"], "`" + blob.replace("`", "` + \"`\" + `") + "`")


def php():
    blob = json.dumps(compact(), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return "<?php\n\n// %s\n\ndeclare(strict_types=1);\n\nnamespace LombokLocale;\n\n/** @internal */\nfinal class Data\n{\n    public const JSON = %s;\n}\n" % (
        HEADER, "'" + blob.replace("\\", "\\\\").replace("'", "\\'") + "'")


TARGETS = {
    "rust/src/data.rs": rust,
    "typescript/src/data.ts": ts,
    "python/lomboklocale/_data.py": py,
    "go/data.go": go,
    "php/src/Data.php": php,
}


def main():
    check = "--check" in sys.argv
    stale = []
    for rel, fn in TARGETS.items():
        text = fn()
        path = ROOT / rel
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if stale:
        sys.exit("stale generated files: " + ", ".join(stale))
    print("ok" if check else "written: " + ", ".join(TARGETS))


if __name__ == "__main__":
    main()
