# Salin ke <Repo>/.github/workflows/ci.yml  (ganti LombokLocale & lomboklocale)
name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lombok-ci:
    uses: codinglombok/.github/.github/workflows/lombok-ci.yml@main
    with:
      repo_name: LombokLocale
      package_name: lomboklocale
