# Salin ke <Repo>/.github/workflows/release.yml  (ganti LombokLocale & lomboklocale)
name: release
on:
  push:
    branches: [main]
jobs:
  lombok-release:
    uses: codinglombok/.github/.github/workflows/lombok-release.yml@main
    with:
      repo_name: LombokLocale
      package_name: lomboklocale
    secrets: inherit
